sudo: required
language: cpp
compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.9 g++-4.9 checkinstall -y --force-yes

install: true

before_script:
  - gcc --version
  - /usr/bin/g++-4.9 --version
  - /usr/bin/gcc-4.9 --version

  - export CXX="g++-4.9"
  - export CC="gcc-4.9"

  - wget https://bitbucket.org/moswald/xunit/downloads/xUnit++.1.3.2.tar.gz
  - tar -zxvf xUnit++.1.3.2.tar.gz
  - pwd
  - mkdir build
  - ls
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release

script:
  - make

after_success:
  - echo "User friendly console Applications Menu for Unix & Linux" 
    | sudo checkinstall -D --install="no" --nodoc 
                   --pkgname "apps" 
                   --pkgversion "1.0" 
                   --pkgrelease "1" 
                   --pkgarch "amd64" 
                   --maintainer "Anton Seliverstov" 
                   --pkgsource "https://github.com/anton-seliverstov/Apps.git" 
                   --pkggroup "misc" 
                   --pkglicense "GNU General Public License, Version 3" 
  - pwd
  - ls
  - dpkg --contents apps_*_amd64.deb
  - sudo dpkg -i apps_*_amd64.deb
  - cd ..
  - pwd
  - ls -aC
  - echo "Testing installation:"
  - ls -l /usr/bin/apps
  - ls -l /usr/bin/generate_apps-rc
  - ls -l /usr/share/man/ru/man1/apps.1.gz
  - ls -l /usr/share/man/ru/man1/generate_apps-rc.1.gz
  - ls -l /usr/share/man/ru/man5/apps-rc.5.gz
  - ls -l /usr/share/man/man1/apps.1.gz
  - ls -l /usr/share/man/man1/generate_apps-rc.1.gz
  - ls -l /usr/share/man/man5/apps-rc.5.gz
  - generate_apps-rc
  - cat ~/.config/apps/apps-rc

notifications:
  email:
    recipients:
      - sendspam@mail2nowhere.com
    on_success: always
    on_failure: always
