.\" Manpage for apps.
.\"
.\" Copyright (C), 2015 Anton Seliverstov (seliverstov.ad@ya.ru)
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file COPYING that comes with the 
.\" man-db distribution.
.\"
.TH man 5 "13 Dec 2015" "1.0" "Справочные страницы apps"
.SH NAME
apps-rc \- Файл конфигурации apps.
.SH ОБЗОР
Apps ищет фай конфигурации в
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
$HOME/.config/apps/apps-rc
.SH ОПИСАНИЕ
.sp
Файл apps-rc имеет XML-подобный синтаксис. 
Apps создана легковесной, чтобы собираться и запускаться почти 
на любом дистрибутиве Unix/Linux,  
поэтому она не поддерживает некоторые тяжёлые возможности XML 
и имеет ряд ограничений.
 Просто следуйте формату сгенерированного файла:
 \- Один тег на строку;
 \- Вложенные папки поддерживаются;
 \- Единственный важный атрибут это "name", остальные по желанию;
 \- Используйте "\-\-" для комментирования строки;
 \- Не используйте в строках специальные символы "\-\-", "/", ">" и "<".
.sp
Файл должен содержать "<apps>" в качестве корневого элемента, 
который содержит все глобальные параметры и само меню приложений. 
Параметры задаются в формате:

.sh
.RS 4
    <prop name="ИМЯ_ПАРАМЕТРА" value="ЗНАЧЕНИЕ_ПАРАМЕТРА"/>
.sp
Доступны следующие параметры:
.sp
    SHOW_CMD (true/false) - показывает значение атрибута "cmd" вместо "name", если "cmd" указан;
.sp
    SHOW_COMMENTS (true/false) - показывает комментарий к категориям и приложениям, если он указан;
.sp
    KEYCODE_MENU_PREVIOUS - переходит к предыдущему элементу меню, при появлении указаной 
последовательности символов. Каждый символ - это трёхзначное число (с нулями впереди). 
Символы разделены пробелами, если их в последовательности больше одного.
Например  "027 091 065" ANSI последовательность, генерируемая системой при нажатии 
кнопки со стрелкой вверх на клавиатуре. (см секцию с примерами);
.sp
    KEYCODE_MENU_NEXT - последовательность символов для перехода к следующему элементу меню;
.sp
    KEYCODE_MENU_IN - войти в категорию по указаной последовательности символов;
.sp
    KEYCODE_MENU_OUT - выйти из текущей категории по указаной последовательности символов;
.sp
    KEYCODE_MENU_RUN - выполнить приложение, если для него указан "cmd" 
атрибут по указаной последовательности символов;
.sp
    KEYCODE_MENU_EXIT - выйти из приложения, оставив последний выделенный элемент в строке консоли;
.sp
    FOLDER_ICON_PRE - текстовая иконка категории, отображаемая перед названием;
.sp
    FOLDER_ICON_POST - текстовая иконка категории, отображаемая за названием, 
если в категории имеются элементы для просмотра;
.sp
    APPLICATION_ICON_PRE - текстовая иконка приложения, отображаемая перед названием;
.sp
    APPLICATION_ICON_POST - текстовая иконка приложения, отображаемая за названием, 
если для приложения указана команда выполнения "cmd".
.sp
.sp
Формат пустой категории:
.sp
    <folder name="ИМЯ_КАТЕГОРИИ" comment="КОММЕНТАРИЙ"/>
.sp
Категории с подкатегориями имеют следующий формат:
.sp
    <folder>
    ...
    </folder>
.sp
Меню apps представлено единственным корневым элементом 
со множеством подкатегорий и приложений с именем (атрибут "name") "root", 
расположенным внутри главного элемента <apps>.
Имя "root" зарезервировано, его нельзя использовать в подкатегориях.
.sp
Формат приложений:
.sp
    <app name="ПУНКТ_МЕНЮ" cmd="КОМАНДА_ОБОЛОЧКИ" comment="КОММЕНТАРИЙ"/>
.sp
Учтите, что комментарии к категориям и приложениям будут показаны 
только если глобальный параметр SHOW_COMMENTS выставлен в "true".
.sp
.SH ПРИМЕРЫ
Вот список известных символьных последовательностей  ANSI, которые распознаёт apps:
.sp
"027 079 080"              F1
.sp
"027 079 081"              F2
.sp
"027 079 082"              F3
.sp
"027 079 083"              F4
.sp
"027 091 049 053 126"      F5
.sp
"027 091 049 055 126"      F6
.sp
"027 091 049 056 126"      F7
.sp
"027 091 049 057 126"      F8
.sp
"027 091 050 048 126"      F9
.sp
"027 091 050 049 126"      F10
.sp
"027 091 050 050 126"      F11
.sp
"027 091 050 051 126"      F12
.sp
"027 091 050 052 126"      F12+
.sp
"027 091 049 126"          Home
.sp
"027 079 072"              Home+
.sp
"027 091 052 126"          End
.sp
"027 079 070"              End+
.sp
"027 091 053 126"          Page-Up
.sp
"027 091 054 126"          Page-Down
.sp
"027 091 050 126"          Insert
.sp
"027 091 065"              Up
.sp
"027 091 066"              Down
.sp
"027 091 068"              Right
.sp
"027 091 067"              Left
.sp
А вот пример содержимого файла apps-rc:
 <apps >
   <prop name="SHOW_CMD" value="false"/>
   <prop name="SHOW_COMMENTS" value="true"/>
   <prop name="KEYCODE_MENU_PREVIOUS" value="027 091 065"/>
   <prop name="KEYCODE_MENU_NEXT" value="027 091 066"/>
   <prop name="KEYCODE_MENU_IN" value="027 091 067"/>
   <prop name="KEYCODE_MENU_OUT" value="027 091 068"/>
   <prop name="KEYCODE_MENU_RUN" value="010"/>
   <prop name="KEYCODE_MENU_EXIT" value="032"/>
   <prop name="FOLDER_ICON_PRE" value="|_| "/>
   <prop name="FOLDER_ICON_POST" value=" ~~"/>
   <prop name="APPLICATION_ICON_PRE" value="| "/>
   <prop name="APPLICATION_ICON_POST" value=" ~~"/>
   <folder name="root">
     <folder name="Мои Программы">
       <folder name="Linux">
         <app name="ping -c4" comment="Попинговать ровно 4 раза"/>
       </folder>
       <app name="ifconfig" cmd="/sbin/ifconfig"/>
   </folder>
 </apps >

.SH SEE ALSO
apps(1)
.SH AUTHOR
Антон Селивёрстов (seliverstov.ad@ya.ru)